version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: auth_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - auth_app_network

volumes:
  db_data:

networks:
  auth_app_network:
    driver: bridge